//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


namespace mark.davison.spacetraders.core.Api;

public interface ISpaceTradersApiClient
{
    string Token { get; set; }
    Task<Response19> AcceptContractAsync(string contractId);
    Task<Response19> AcceptContractAsync(string contractId, CancellationToken cancellationToken);
    Task<Response28> CreateChartAsync(string shipSymbol);
    Task<Response28> CreateChartAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response44> CreateShipShipScanAsync(string shipSymbol);
    Task<Response44> CreateShipShipScanAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response42> CreateShipSystemScanAsync(string shipSymbol);
    Task<Response42> CreateShipSystemScanAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response43> CreateShipWaypointScanAsync(string shipSymbol);
    Task<Response43> CreateShipWaypointScanAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response31> CreateSurveyAsync(string shipSymbol);
    Task<Response31> CreateSurveyAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response20> DeliverContractAsync(Body3 body, string contractId);
    Task<Response20> DeliverContractAsync(Body3 body, string contractId, CancellationToken cancellationToken);
    Task<Response30> DockShipAsync(string shipSymbol);
    Task<Response30> DockShipAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response32> ExtractResourcesAsync(Body6 body, string shipSymbol);
    Task<Response32> ExtractResourcesAsync(Body6 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response34> ExtractResourcesWithSurveyAsync(Survey body, string shipSymbol);
    Task<Response34> ExtractResourcesWithSurveyAsync(Survey body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response21> FulfillContractAsync(string contractId);
    Task<Response21> FulfillContractAsync(string contractId, CancellationToken cancellationToken);
    Task<Response16> GetAgentAsync(string agentSymbol);
    Task<Response16> GetAgentAsync(string agentSymbol, CancellationToken cancellationToken);
    Task<Response15> GetAgentsAsync(int? page, int? limit);
    Task<Response15> GetAgentsAsync(int? page, int? limit, CancellationToken cancellationToken);
    Task<Response10> GetConstructionAsync(string systemSymbol, string waypointSymbol);
    Task<Response10> GetConstructionAsync(string systemSymbol, string waypointSymbol, CancellationToken cancellationToken);
    Task<Response18> GetContractAsync(string contractId);
    Task<Response18> GetContractAsync(string contractId, CancellationToken cancellationToken);
    Task<Response17> GetContractsAsync(int? page, int? limit);
    Task<Response17> GetContractsAsync(int? page, int? limit, CancellationToken cancellationToken);
    Task<Response13> GetFactionAsync(string factionSymbol);
    Task<Response13> GetFactionAsync(string factionSymbol, CancellationToken cancellationToken);
    Task<Response12> GetFactionsAsync(int? page, int? limit);
    Task<Response12> GetFactionsAsync(int? page, int? limit, CancellationToken cancellationToken);
    Task<Response9> GetJumpGateAsync(string systemSymbol, string waypointSymbol);
    Task<Response9> GetJumpGateAsync(string systemSymbol, string waypointSymbol, CancellationToken cancellationToken);
    Task<Response7> GetMarketAsync(string systemSymbol, string waypointSymbol);
    Task<Response7> GetMarketAsync(string systemSymbol, string waypointSymbol, CancellationToken cancellationToken);
    Task<Response49> GetMountsAsync(string shipSymbol);
    Task<Response49> GetMountsAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response14> GetMyAgentAsync();
    Task<Response14> GetMyAgentAsync(CancellationToken cancellationToken);
    Task<Response24> GetMyShipAsync(string shipSymbol);
    Task<Response24> GetMyShipAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response25> GetMyShipCargoAsync(string shipSymbol);
    Task<Response25> GetMyShipCargoAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response22> GetMyShipsAsync(int? page, int? limit);
    Task<Response22> GetMyShipsAsync(int? page, int? limit, CancellationToken cancellationToken);
    Task<Response29> GetShipCooldownAsync(string shipSymbol);
    Task<Response29> GetShipCooldownAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response39> GetShipNavAsync(string shipSymbol);
    Task<Response39> GetShipNavAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response8> GetShipyardAsync(string systemSymbol, string waypointSymbol);
    Task<Response8> GetShipyardAsync(string systemSymbol, string waypointSymbol, CancellationToken cancellationToken);
    Task<Response> GetStatusAsync();
    Task<Response> GetStatusAsync(CancellationToken cancellationToken);
    Task<Response4> GetSystemAsync(string systemSymbol);
    Task<Response4> GetSystemAsync(string systemSymbol, CancellationToken cancellationToken);
    Task<Response3> GetSystemsAsync(int? page, int? limit);
    Task<Response3> GetSystemsAsync(int? page, int? limit, CancellationToken cancellationToken);
    Task<Response5> GetSystemWaypointsAsync(int? page, int? limit, WaypointType? type, WaypointTraitSymbol? traits, string systemSymbol);
    Task<Response5> GetSystemWaypointsAsync(int? page, int? limit, WaypointType? type, WaypointTraitSymbol? traits, string systemSymbol, CancellationToken cancellationToken);
    Task<Response6> GetWaypointAsync(string systemSymbol, string waypointSymbol);
    Task<Response6> GetWaypointAsync(string systemSymbol, string waypointSymbol, CancellationToken cancellationToken);
    Task<Response50> InstallMountAsync(Body15 body, string shipSymbol);
    Task<Response50> InstallMountAsync(Body15 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response35> JettisonAsync(Body7 body, string shipSymbol);
    Task<Response35> JettisonAsync(Body7 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response36> JumpShipAsync(Body8 body, string shipSymbol);
    Task<Response36> JumpShipAsync(Body8 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response37> NavigateShipAsync(Body9 body, string shipSymbol);
    Task<Response37> NavigateShipAsync(Body9 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response48> NegotiateContractAsync(string shipSymbol);
    Task<Response48> NegotiateContractAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response26> OrbitShipAsync(string shipSymbol);
    Task<Response26> OrbitShipAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response38> PatchShipNavAsync(Body10 body, string shipSymbol);
    Task<Response38> PatchShipNavAsync(Body10 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response46> PurchaseCargoAsync(Body13 body, string shipSymbol);
    Task<Response46> PurchaseCargoAsync(Body13 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response23> PurchaseShipAsync(Body4 body);
    Task<Response23> PurchaseShipAsync(Body4 body, CancellationToken cancellationToken);
    Task<Response45> RefuelShipAsync(Body12 body, string shipSymbol);
    Task<Response45> RefuelShipAsync(Body12 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response2> RegisterAsync(RegisterBody body);
    Task<Response2> RegisterAsync(RegisterBody body, CancellationToken cancellationToken);
    Task<Response51> RemoveMountAsync(Body16 body, string shipSymbol);
    Task<Response51> RemoveMountAsync(Body16 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response41> SellCargoAsync(SellCargoRequest body, string shipSymbol);
    Task<Response41> SellCargoAsync(SellCargoRequest body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response27> ShipRefineAsync(Body5 body, string shipSymbol);
    Task<Response27> ShipRefineAsync(Body5 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response33> SiphonResourcesAsync(string shipSymbol);
    Task<Response33> SiphonResourcesAsync(string shipSymbol, CancellationToken cancellationToken);
    Task<Response11> SupplyConstructionAsync(Body2 body, string systemSymbol, string waypointSymbol);
    Task<Response11> SupplyConstructionAsync(Body2 body, string systemSymbol, string waypointSymbol, CancellationToken cancellationToken);
    Task<Response47> TransferCargoAsync(Body14 body, string shipSymbol);
    Task<Response47> TransferCargoAsync(Body14 body, string shipSymbol, CancellationToken cancellationToken);
    Task<Response40> WarpShipAsync(Body11 body, string shipSymbol);
    Task<Response40> WarpShipAsync(Body11 body, string shipSymbol, CancellationToken cancellationToken);
}