global using mark.davison.common.client.Ignition;
global using mark.davison.common.client.web.abstractions.Authentication;
global using mark.davison.common.client.web.Authentication;
global using mark.davison.spacetraders.web.components.Ignition;
global using mark.davison.spacetraders.web.features;
global using mark.davison.spacetraders.web.ui;
global using mark.davison.spacetraders.web.ui.Ignition;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;